### ISSUE TITLE
BUG restore.sh script relies on optional annotation

### ISSUE THREAD

**Issue by Heiko-san** [clastix/kamaji-etcd#40]
Hi,

we tried how well an etcd backup restore works atm.
We use kamaji v0.3.3 together with cluster-api v1.5.0 with infrastructure-vsphere v1.7.0 and your kamaji plugin control-plane-kamaji v0.3.0.

We created an additional datastore of type etcd using your helm chart clastix/kamaji-etcd.
The backup job to s3 succeeds and we were able to restore the etcd using your restore.sh script, but we had to make some changes to it:

``` diff
diff --git a/scripts/restore.sh b/scripts/restore.sh
index dddec4f..dc8b1f8 100755
--- a/scripts/restore.sh
+++ b/scripts/restore.sh
@@ -19,6 +19,7 @@ set -eu -o pipefail
 KAMAJI_TCP_SNAP_URL=$1
 
 # Service variables
+KAMAJI_PODS_JSON_BEFORE=$(kubectl get pods -n $ETCD_NAMESPACE -l app.kubernetes.io/instance=$ETCD_NAME -o json)
 KAMAJI_PODS_JSON="kubectl get pods -n $ETCD_NAMESPACE -l app.kubernetes.io/instance=$ETCD_NAME -o json"
 KAMAJI_TCP_SNAP="snapshot.db"
 TMP_FOLDER="/tmp"
@@ -105,8 +106,8 @@ etcdFolderSwitch() {
     PVC_VOLUMENAME=$($KAMAJI_PVC_JSON |\
       jq -j '.spec.volumeName')
   
-    PVC_NODE=$($KAMAJI_PVC_JSON |\
-      jq -j '.metadata.annotations["volume.kubernetes.io/selected-node"]')
+    PVC_NODE=$(echo $KAMAJI_PODS_JSON_BEFORE |\
+      jq -r --arg pvc_name $DATA '.items[] | select(.spec.volumes[].persistentVolumeClaim.claimName == $pvc_name) | .spec.nodeName')
  
   cat <<EOF | kubectl apply -f -
   apiVersion: batch/v1
```

I'm aware this may not be the best option to fix it, but the underlying problem seems to be:

The annotation "volume.kubernetes.io/selected-node" does not necessarily exist.
We use trident as CSI storage provider and we think it relates to this, that the annotation is missing for us.
However this means it may not be the best option to rely on this annotation.

**Comment by prometherion** [comment]
> The annotation "volume.kubernetes.io/selected-node" does not necessarily exist.
> We use trident as CSI storage provider and we think it relates to this, that the annotation is missing for us.
> However this means it may not be the best option to rely on this annotation.

According to the [Kubernetes documentation](https://kubernetes.io/docs/reference/labels-annotations-taints/#volume-kubernetes-io-selected-node):

> This annotation is added to a PVC that is triggered by a scheduler to be dynamically provisioned.
> Its value is the name of the selected node.

Before addressing this on Kamaji, which we are always open to supporting as many use cases as possible, I'd try raising the issue before on CSI Trident maintainers: it's weird the annotation is not there, since it's required by the Kubernetes contract about persistent storage.

Please, feel free to reference this discussion so we can be kept posted about it.

**Comment by Heiko-san** [comment]
Seems legit to me. :) However I wanted to provide the information, that it might not be a reliable annotation.

**Comment by YvosOnTheHub** [comment]
Hi @Heiko-san,

Just performed some tests with CSI Astra Trident.
The annotation you are looking for seems to be linked to the Storage Class parameter:
`volumeBindingMode: WaitForFirstConsumer`

When I position this parameter, my PVC get the annotation you are looking for:
```
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
               volume.kubernetes.io/selected-node: rhel2
```

btw, this SC parameter is often used with CSI Topology, but can also be used out of this context.

What does your SC look like?

**Comment by bsctl** [comment]
Closing by inactivity.
